[package]
name = "day_18"
version = "0.1.0"
authors = ["Mariano Heller <marianofheller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom="6.1.2"
utils = { path = "../../utils" }